[Jupyter] [Shell] timestamps git creds (#929)

diff --git a/stable/jupyter/templates/jupyter-configmap.yaml b/stable/jupyter/templates/jupyter-configmap.yaml
--- a/stable/jupyter/templates/jupyter-configmap.yaml
+++ b/stable/jupyter/templates/jupyter-configmap.yaml
@@ -36,17 +36,25 @@ data:
     #!/usr/bin/env bash
     set -e
 
+    ## log + timer
+    start=${SECONDS}
+    log () {
+      echo [$(( SECONDS - start ))s] "$*"
+    }
+
 {{ include "v3io-configs.script.lookupService" . | indent 4 }}
 
     ## Reset .bashrc on revision update
     BASHRC_REV=1
-    if ! $(grep -q IGZ_BASHRC_REV_${BASHRC_REV} ${HOME}/.bashrc); then
+    if ! $(grep -q IGZ_BASHRC_REV_${BASHRC_REV} ${HOME}/.bashrc 2>/dev/null); then
+      log 'Reset .bashrc on revision update'
       echo "#IGZ_BASHRC_REV_${BASHRC_REV}" > ${HOME}/.bashrc
     fi
 
 
     ## Kubectl autocompletion
     if [ "$(grep --count 'KUBECTL AUTOCOMPLETION' ${HOME}/.bashrc)" == "0" ]; then
+      log 'Configure kubectl autocompletion'
       cat << EOF >> ${HOME}/.bashrc
     # ----- KUBECTL AUTOCOMPLETION -----
     if [ -f /etc/bash_completion ]; then
@@ -62,7 +70,8 @@ data:
 
 
     ## Create conda env dir (fuse), populate .condarc and init
-    if [ ! -d "${HOME}/.conda/envs" ]; then 
+    if [ ! -d "${HOME}/.conda/envs" ]; then
+      log 'Configure conda'
       mkdir -p ${HOME}/.conda/envs
     fi
     if [ ! -e "${HOME}/.condarc" ]; then
@@ -84,6 +93,7 @@ data:
 
     ## Init commands
 {{- if .Values.initCommands }}
+    log 'Configure init commands'
     mkdir -p ${HOME}/.igz
 {{- range $index, $initCmd := .Values.initCommands }}
     if [ ! -e "${HOME}/.igz/.{{ $initCmd.name }}" ]; then
@@ -96,6 +106,7 @@ data:
 
     ## Spark
 {{- if .Values.spark }}
+    log 'Configure spark'
     cat << EOF >> ${SPARK_HOME}/conf/spark-defaults.conf
     spark.master=spark://{{ .Values.spark.hostname }}:{{ .Values.spark.port }}
     spark.driver.host=$(hostname -i)
@@ -116,6 +127,7 @@ data:
 
     ## Presto
 {{- if .Values.presto }}
+    log 'Configure presto'
     rm -rf ${IGUAZIO_HOME}/.presto_alias
     touch ${IGUAZIO_HOME}/.trino_history
 {{- if .Values.presto.keystoreBinary }}
@@ -148,6 +160,7 @@ data:
 
     ## Hive
 {{- if .Values.hive }}
+    log 'Configure hive'
     echo alias hive=\"JAVA_HOME=${IGUAZIO_HOME}/jdk-8u181 ${HIVE_HOME}/bin/hive -hiveconf hive.exec.scratchdir={{ .Values.hive.scratchDirPrefix }}/${V3IO_USERNAME}/hive -hiveconf hive.metastore.uris=thrift://{{ .Values.hive.metastore.hostname }}:{{ .Values.hive.metastore.port }} \$@\" >> ${IGUAZIO_HOME}/.hive_alias
     if [ "$(grep --count 'HIVE CONFIG' ${HOME}/.bashrc)" == "0" ]; then
       cat << EOF >> ${HOME}/.bashrc
@@ -162,6 +175,7 @@ data:
 
     ## Download extra binaries
 {{- if and .Values.v3io.downloadBinaries }}
+    log 'Download extra binaries'
 {{- range $binary, $url := .Values.v3io.downloadBinaries }}
     curl --disable -sSL -o ${IGUAZIO_HOME}/bin/{{ $binary }} {{ $url }}
     chmod +x ${IGUAZIO_HOME}/bin/{{ $binary }}
@@ -171,6 +185,7 @@ data:
 
     ## TSDB
 {{- if and .Values.v3io.tsdbctl .Values.v3io.tsdbctl.download }}
+    log 'Configure TSDB'
     curl --disable -sSL -o ${IGUAZIO_HOME}/bin/tsdbctl {{ .Values.v3io.tsdbctl.download }}
     chmod +x ${IGUAZIO_HOME}/bin/tsdbctl
     rm -f ${IGUAZIO_HOME}/.tsdb_alias
@@ -191,6 +206,7 @@ data:
     ## Iguazio terminal logo
 {{- if .Values.config.logo }}
     if [ "$(grep --count 'LOGO CONFIG' ${HOME}/.bashrc)" == "0" ]; then
+      log 'Configure iguazio logo'
       echo "# ----- LOGO CONFIG -----" >> ${HOME}/.bashrc
       echo "echo ''" >> ${HOME}/.bashrc
       echo "printf '\033[?7l'" >> ${HOME}/.bashrc
@@ -205,6 +221,7 @@ data:
 
     ## Prompt config
     if [ "$(grep --count 'IGUAZIO PROMPT CONFIG' ${HOME}/.bashrc)" == "0" ]; then
+      log 'Configure prompt'
       cp ${CONDA_HOME}/.bash_prompt.sh ${HOME}
       cat << EOF >> ${HOME}/.bashrc
     # ----- IGUAZIO PROMPT CONFIG -----
@@ -218,6 +235,7 @@ data:
 
     ## SSH config
 {{- if .Values.sshServer.enabled }}
+    log 'Configure SSH'
     cp /var/run/iguazio/secrets/ssh/* ${IGUAZIO_HOME}/.ssh
     cat << EOF >> /etc/ssh/sshd_config
     PasswordAuthentication no
@@ -233,10 +251,11 @@ data:
     source ${HOME}/.bashrc
     EOF
 {{- end }}
-
     echo "source ${HOME}/.bashrc" > ${HOME}/.bash_profile
 
+
     ## Vim config
+    log 'Configure vim'
     touch ${HOME}/.viminfo
     chmod a+w ${HOME}/.viminfo
     # Remove term= line from .vimrc - setting causes some keys (for ex. del) not to work
@@ -245,16 +264,23 @@ data:
     fi
 
 
-    ## Prevent git from failing on fuse mount (not owned by iguazio user)
+    ## Git config
+    log 'Configure git'
+    # Prevent git from failing on fuse mount (not owned by iguazio user)
     # https://stackoverflow.com/questions/72978485/ubuntu-20-04-git-submodule-update-failed-with-fatal-detected-dubious-ownershi
-    if [ "$(git config --global --get safe.directory)" != "*" ]; then
+    if [ "$(git config --global --get safe.directory)" == "" ]; then
       git config --global --add safe.directory '*'
+    fi
+    # Store credentials in cache for multi pushing
+    if [ "$(git config --global --get credential.helper)" == "" ]; then
+      git config --global --add credential.helper store
     fi
 
 
     ## Block conda/pip installs on prebaked conda envs
     # https://github.com/conda/conda/issues/7791
     if [ "$(grep --count 'BLOCK INSTALL ON CONDA BASE' ${HOME}/.bashrc)" == "0" ]; then
+      log 'Block conda, pip on prebaked envs'
       cat << EOF >> ${HOME}/.bashrc
     # ----- BLOCK INSTALL ON CONDA BASE -----
     function pip(){
@@ -292,6 +318,7 @@ data:
     fi    
     # reset ipython_config.py on revision update
     if ! $(grep -q IGZ_IPYTHON_CONFIG_REV_${IPYTHON_CONFIG_REV} ${IPYTHON_CONFIG_SCRIPT} 2>/dev/null); then
+      log 'Configure ipython'
       cat << EOF > ${IPYTHON_CONFIG_SCRIPT}
     #IGZ_IPYTHON_CONFIG_REV_${IPYTHON_CONFIG_REV}
     import pkg_resources
@@ -314,6 +341,7 @@ data:
 
     ## Create bashrc for non-interactive SSH logins
     if [ ! -e "${HOME}/.bashrc-noninteractive" ]; then
+      log 'Configure non-interactive bashrc'
       cat << EOF > ${HOME}/.bashrc-noninteractive
     # bashrc for non-interactive SSH logins
     EOF
@@ -325,6 +353,7 @@ data:
 
 
     # PIP persistency on fuse mount for /conda (docker) envs
+    log 'Configure PIP persistency for prebaked envs'
     # jupyter (needs special handling for jupyter.fullname in case of multiple jupy envs per user):
     if [ ! -e "${CONDA_HOME}/envs/jupyter/etc/conda/activate.d/env_vars.sh" ]; then
       cat << EOF > ${CONDA_HOME}/envs/jupyter/etc/conda/activate.d/env_vars.sh
@@ -378,6 +407,7 @@ data:
 
 
     # Set jupyter directories to fuse (persistent)
+    log 'Configure jupyter'
     # https://jupyterlab.readthedocs.io/en/stable/user/directories.html
     # https://docs.jupyter.org/en/latest/use/jupyter-directories.html
     export JUPYTERLAB_DIR=${HOME}/.{{ template "jupyter.fullname" . }}/lab
@@ -445,6 +475,7 @@ data:
     ALIGN_MLRUN_REV=1
     # reset align_mlrun on revision update
     if ! $(grep -q IGZ_ALIGN_MLRUN_REV_${ALIGN_MLRUN_REV} ${ALIGN_MLRUN_SCRIPT} 2>/dev/null); then
+      log 'Configure align_mlrun.sh script'
       cat << EOF > ${ALIGN_MLRUN_SCRIPT}
     #IGZ_ALIGN_MLRUN_REV_${ALIGN_MLRUN_REV}
     if [ "\${CONDA_DEFAULT_ENV-}" = "base" ]; then
@@ -477,6 +508,7 @@ data:
     ## Tutorials
     mkdir -p ${HOME}/.igz
     if [ ! -e "${HOME}/.igz/.getting-started" ] && [ ! -z ${IGZ_JUPYTER_TUTORIALS_URL} ] && [ ! -z ${IGZ_MLRUN_DEMOS_URL} ]; then
+      log 'Configure tutorials'
       curl -L ${IGZ_JUPYTER_TUTORIALS_URL} -o /tmp/jupyter-tutorials
       curl -L ${IGZ_MLRUN_DEMOS_URL} -o /tmp/mlrun-demos
       TUTORIALS_SCRIPT_FILE=`tar --list --file=/tmp/jupyter-tutorials|grep igz-tutorials-get.sh`
@@ -504,6 +536,7 @@ data:
     fi
 
     ## Startup hooks
+    log 'Configure startup hooks'
     if [ -e "/igz/startup-hook.sh" ]; then
         /bin/bash /igz/startup-hook.sh || true
     fi
@@ -513,5 +546,6 @@ data:
     fi
 
     ## Start Jupyter
+    log 'Starting jupyter'
     source activate jupyter
     jupyter lab --no-browser $@
